version: '3.6'

services:
  arke-maker:
    restart: always
    image: "gcr.io/openware-production/arke:2.3.1"
    env_file:
      - ../config/arke.env
    volumes:
      - ../config/arke/strategies.yml:/home/app/config/strategies.yml
    command: bundle exec ./bin/arke start
